# Generated by Django 5.1.6 on 2025-02-12 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='thread_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
